// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -305547460;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__accept_transfer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    request_id: impl CstDecode<String>,
    protocol: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_transfer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_request_id = request_id.cst_decode();
            let api_protocol = protocol.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::accept_transfer(api_request_id, api_protocol).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__get_devices_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_devices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::get_devices().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__get_protocols_impl() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco
{
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_protocols",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::get_protocols()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__init_engine_impl(
    device_name: impl CstDecode<Option<String>>,
    save_dir: impl CstDecode<Option<String>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_engine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_device_name = device_name.cst_decode();
            let api_save_dir = save_dir.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::init_engine(api_device_name, api_save_dir)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__is_engine_running_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_engine_running",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::is_engine_running())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__reject_transfer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    request_id: impl CstDecode<String>,
    protocol: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reject_transfer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_request_id = request_id.cst_decode();
            let api_protocol = protocol.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::reject_transfer(api_request_id, api_protocol).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__scan_devices_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_devices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::scan_devices().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__send_files_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    device_id: impl CstDecode<String>,
    file_paths: impl CstDecode<Vec<String>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_files",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.cst_decode();
            let api_file_paths = file_paths.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::send_files(api_device_id, api_file_paths).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__start_engine_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_engine",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::start_engine().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__stop_engine_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_engine",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::stop_engine().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__subscribe_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    callback: impl CstDecode<flutter_rust_bridge::DartOpaque>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "subscribe_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_callback =
                decode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(callback.cst_decode());
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::subscribe_events(api_callback).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: related_funcs

fn decode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
    dart_opaque: flutter_rust_bridge::DartOpaque,
) -> impl Fn(crate::api::FfiEvent) -> flutter_rust_bridge::DartFnFuture<()> {
    use flutter_rust_bridge::IntoDart;

    async fn body(dart_opaque: flutter_rust_bridge::DartOpaque, arg0: crate::api::FfiEvent) -> () {
        let args = vec![arg0.into_into_dart().into_dart()];
        let message = FLUTTER_RUST_BRIDGE_HANDLER
            .dart_fn_invoke(dart_opaque, args)
            .await;

        let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
        let action = deserializer.cursor.read_u8().unwrap();
        let ans = match action {
            0 => std::result::Result::Ok(<()>::sse_decode(&mut deserializer)),
            1 => std::result::Result::Err(
                <flutter_rust_bridge::for_generated::anyhow::Error>::sse_decode(&mut deserializer),
            ),
            _ => unreachable!(),
        };
        deserializer.end();
        let ans = ans.expect("Dart throws exception but Rust side assume it is not failable");
        ans
    }

    move |arg0: crate::api::FfiEvent| {
        flutter_rust_bridge::for_generated::convert_into_dart_fn_future(body(
            dart_opaque.clone(),
            arg0,
        ))
    }
}

// Section: dart2rust

impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<f64> for f64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> f64 {
        self
    }
}
impl CstDecode<isize> for isize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> isize {
        self
    }
}
impl CstDecode<u64> for u64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u64 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl CstDecode<usize> for usize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> usize {
        self
    }
}
impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for flutter_rust_bridge::DartOpaque {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { flutter_rust_bridge::for_generated::sse_decode_dart_opaque(inner) };
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::FfiDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_deviceType = <String>::sse_decode(deserializer);
        let mut var_address = <String>::sse_decode(deserializer);
        let mut var_protocol = <String>::sse_decode(deserializer);
        return crate::api::FfiDevice {
            id: var_id,
            name: var_name,
            device_type: var_deviceType,
            address: var_address,
            protocol: var_protocol,
        };
    }
}

impl SseDecode for crate::api::FfiEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_device = <crate::api::FfiDevice>::sse_decode(deserializer);
                return crate::api::FfiEvent::DeviceDiscovered { device: var_device };
            }
            1 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                return crate::api::FfiEvent::DeviceLost {
                    device_id: var_deviceId,
                };
            }
            2 => {
                let mut var_request = <crate::api::FfiTransferRequest>::sse_decode(deserializer);
                return crate::api::FfiEvent::TransferRequested {
                    request: var_request,
                };
            }
            3 => {
                let mut var_progress = <crate::api::FfiTransferProgress>::sse_decode(deserializer);
                return crate::api::FfiEvent::TransferProgress {
                    progress: var_progress,
                };
            }
            4 => {
                let mut var_transferId = <String>::sse_decode(deserializer);
                return crate::api::FfiEvent::TransferCompleted {
                    transfer_id: var_transferId,
                };
            }
            5 => {
                let mut var_transferId = <String>::sse_decode(deserializer);
                let mut var_error = <String>::sse_decode(deserializer);
                return crate::api::FfiEvent::TransferFailed {
                    transfer_id: var_transferId,
                    error: var_error,
                };
            }
            6 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::FfiEvent::Error {
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::FfiFileInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_size = <u64>::sse_decode(deserializer);
        let mut var_mimeType = <Option<String>>::sse_decode(deserializer);
        return crate::api::FfiFileInfo {
            id: var_id,
            name: var_name,
            size: var_size,
            mime_type: var_mimeType,
        };
    }
}

impl SseDecode for crate::api::FfiLocalInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deviceName = <String>::sse_decode(deserializer);
        let mut var_saveDir = <String>::sse_decode(deserializer);
        let mut var_protocols = <Vec<String>>::sse_decode(deserializer);
        return crate::api::FfiLocalInfo {
            device_name: var_deviceName,
            save_dir: var_saveDir,
            protocols: var_protocols,
        };
    }
}

impl SseDecode for crate::api::FfiTransferProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_transferId = <String>::sse_decode(deserializer);
        let mut var_fileName = <String>::sse_decode(deserializer);
        let mut var_bytesSent = <u64>::sse_decode(deserializer);
        let mut var_totalBytes = <u64>::sse_decode(deserializer);
        let mut var_progress = <f64>::sse_decode(deserializer);
        return crate::api::FfiTransferProgress {
            transfer_id: var_transferId,
            file_name: var_fileName,
            bytes_sent: var_bytesSent,
            total_bytes: var_totalBytes,
            progress: var_progress,
        };
    }
}

impl SseDecode for crate::api::FfiTransferRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_requestId = <String>::sse_decode(deserializer);
        let mut var_fromDevice = <crate::api::FfiDevice>::sse_decode(deserializer);
        let mut var_files = <Vec<crate::api::FfiFileInfo>>::sse_decode(deserializer);
        let mut var_totalSize = <u64>::sse_decode(deserializer);
        return crate::api::FfiTransferRequest {
            request_id: var_requestId,
            from_device: var_fromDevice,
            files: var_files,
            total_size: var_totalSize,
        };
    }
}

impl SseDecode for isize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FfiDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiDevice>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FfiFileInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiFileInfo>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiDevice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.device_type.into_into_dart().into_dart(),
            self.address.into_into_dart().into_dart(),
            self.protocol.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiDevice {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiDevice> for crate::api::FfiDevice {
    fn into_into_dart(self) -> crate::api::FfiDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::FfiEvent::DeviceDiscovered { device } => {
                [0.into_dart(), device.into_into_dart().into_dart()].into_dart()
            }
            crate::api::FfiEvent::DeviceLost { device_id } => {
                [1.into_dart(), device_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::FfiEvent::TransferRequested { request } => {
                [2.into_dart(), request.into_into_dart().into_dart()].into_dart()
            }
            crate::api::FfiEvent::TransferProgress { progress } => {
                [3.into_dart(), progress.into_into_dart().into_dart()].into_dart()
            }
            crate::api::FfiEvent::TransferCompleted { transfer_id } => {
                [4.into_dart(), transfer_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::FfiEvent::TransferFailed { transfer_id, error } => [
                5.into_dart(),
                transfer_id.into_into_dart().into_dart(),
                error.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::FfiEvent::Error { message } => {
                [6.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiEvent> for crate::api::FfiEvent {
    fn into_into_dart(self) -> crate::api::FfiEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiFileInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.size.into_into_dart().into_dart(),
            self.mime_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiFileInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiFileInfo> for crate::api::FfiFileInfo {
    fn into_into_dart(self) -> crate::api::FfiFileInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiLocalInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.device_name.into_into_dart().into_dart(),
            self.save_dir.into_into_dart().into_dart(),
            self.protocols.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiLocalInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiLocalInfo> for crate::api::FfiLocalInfo {
    fn into_into_dart(self) -> crate::api::FfiLocalInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiTransferProgress {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.transfer_id.into_into_dart().into_dart(),
            self.file_name.into_into_dart().into_dart(),
            self.bytes_sent.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
            self.progress.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiTransferProgress
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiTransferProgress>
    for crate::api::FfiTransferProgress
{
    fn into_into_dart(self) -> crate::api::FfiTransferProgress {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiTransferRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.request_id.into_into_dart().into_dart(),
            self.from_device.into_into_dart().into_dart(),
            self.files.into_into_dart().into_dart(),
            self.total_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiTransferRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiTransferRequest>
    for crate::api::FfiTransferRequest
{
    fn into_into_dart(self) -> crate::api::FfiTransferRequest {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for flutter_rust_bridge::DartOpaque {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <usize>::sse_encode(self.encode(), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::FfiDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.device_type, serializer);
        <String>::sse_encode(self.address, serializer);
        <String>::sse_encode(self.protocol, serializer);
    }
}

impl SseEncode for crate::api::FfiEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::FfiEvent::DeviceDiscovered { device } => {
                <i32>::sse_encode(0, serializer);
                <crate::api::FfiDevice>::sse_encode(device, serializer);
            }
            crate::api::FfiEvent::DeviceLost { device_id } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(device_id, serializer);
            }
            crate::api::FfiEvent::TransferRequested { request } => {
                <i32>::sse_encode(2, serializer);
                <crate::api::FfiTransferRequest>::sse_encode(request, serializer);
            }
            crate::api::FfiEvent::TransferProgress { progress } => {
                <i32>::sse_encode(3, serializer);
                <crate::api::FfiTransferProgress>::sse_encode(progress, serializer);
            }
            crate::api::FfiEvent::TransferCompleted { transfer_id } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(transfer_id, serializer);
            }
            crate::api::FfiEvent::TransferFailed { transfer_id, error } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(transfer_id, serializer);
                <String>::sse_encode(error, serializer);
            }
            crate::api::FfiEvent::Error { message } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::FfiFileInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <u64>::sse_encode(self.size, serializer);
        <Option<String>>::sse_encode(self.mime_type, serializer);
    }
}

impl SseEncode for crate::api::FfiLocalInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.device_name, serializer);
        <String>::sse_encode(self.save_dir, serializer);
        <Vec<String>>::sse_encode(self.protocols, serializer);
    }
}

impl SseEncode for crate::api::FfiTransferProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.transfer_id, serializer);
        <String>::sse_encode(self.file_name, serializer);
        <u64>::sse_encode(self.bytes_sent, serializer);
        <u64>::sse_encode(self.total_bytes, serializer);
        <f64>::sse_encode(self.progress, serializer);
    }
}

impl SseEncode for crate::api::FfiTransferRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.request_id, serializer);
        <crate::api::FfiDevice>::sse_encode(self.from_device, serializer);
        <Vec<crate::api::FfiFileInfo>>::sse_encode(self.files, serializer);
        <u64>::sse_encode(self.total_size, serializer);
    }
}

impl SseEncode for isize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_i64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FfiDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiDevice>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FfiFileInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiFileInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<flutter_rust_bridge::DartOpaque> for *const std::ffi::c_void {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::DartOpaque {
            unsafe { flutter_rust_bridge::for_generated::cst_decode_dart_opaque(self as _) }
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::api::FfiDevice> for *mut wire_cst_ffi_device {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiDevice {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::FfiDevice>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::FfiTransferProgress> for *mut wire_cst_ffi_transfer_progress {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiTransferProgress {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::FfiTransferProgress>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::FfiTransferRequest> for *mut wire_cst_ffi_transfer_request {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiTransferRequest {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::FfiTransferRequest>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::FfiDevice> for wire_cst_ffi_device {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiDevice {
            crate::api::FfiDevice {
                id: self.id.cst_decode(),
                name: self.name.cst_decode(),
                device_type: self.device_type.cst_decode(),
                address: self.address.cst_decode(),
                protocol: self.protocol.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiEvent> for wire_cst_ffi_event {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiEvent {
            match self.tag {
                0 => {
                    let ans = unsafe { self.kind.DeviceDiscovered };
                    crate::api::FfiEvent::DeviceDiscovered {
                        device: ans.device.cst_decode(),
                    }
                }
                1 => {
                    let ans = unsafe { self.kind.DeviceLost };
                    crate::api::FfiEvent::DeviceLost {
                        device_id: ans.device_id.cst_decode(),
                    }
                }
                2 => {
                    let ans = unsafe { self.kind.TransferRequested };
                    crate::api::FfiEvent::TransferRequested {
                        request: ans.request.cst_decode(),
                    }
                }
                3 => {
                    let ans = unsafe { self.kind.TransferProgress };
                    crate::api::FfiEvent::TransferProgress {
                        progress: ans.progress.cst_decode(),
                    }
                }
                4 => {
                    let ans = unsafe { self.kind.TransferCompleted };
                    crate::api::FfiEvent::TransferCompleted {
                        transfer_id: ans.transfer_id.cst_decode(),
                    }
                }
                5 => {
                    let ans = unsafe { self.kind.TransferFailed };
                    crate::api::FfiEvent::TransferFailed {
                        transfer_id: ans.transfer_id.cst_decode(),
                        error: ans.error.cst_decode(),
                    }
                }
                6 => {
                    let ans = unsafe { self.kind.Error };
                    crate::api::FfiEvent::Error {
                        message: ans.message.cst_decode(),
                    }
                }
                _ => unreachable!(),
            }
        }
    }
    impl CstDecode<crate::api::FfiFileInfo> for wire_cst_ffi_file_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiFileInfo {
            crate::api::FfiFileInfo {
                id: self.id.cst_decode(),
                name: self.name.cst_decode(),
                size: self.size.cst_decode(),
                mime_type: self.mime_type.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiLocalInfo> for wire_cst_ffi_local_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiLocalInfo {
            crate::api::FfiLocalInfo {
                device_name: self.device_name.cst_decode(),
                save_dir: self.save_dir.cst_decode(),
                protocols: self.protocols.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiTransferProgress> for wire_cst_ffi_transfer_progress {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiTransferProgress {
            crate::api::FfiTransferProgress {
                transfer_id: self.transfer_id.cst_decode(),
                file_name: self.file_name.cst_decode(),
                bytes_sent: self.bytes_sent.cst_decode(),
                total_bytes: self.total_bytes.cst_decode(),
                progress: self.progress.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiTransferRequest> for wire_cst_ffi_transfer_request {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiTransferRequest {
            crate::api::FfiTransferRequest {
                request_id: self.request_id.cst_decode(),
                from_device: self.from_device.cst_decode(),
                files: self.files.cst_decode(),
                total_size: self.total_size.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<String>> for *mut wire_cst_list_String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::FfiDevice>> for *mut wire_cst_list_ffi_device {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::FfiDevice> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::FfiFileInfo>> for *mut wire_cst_list_ffi_file_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::FfiFileInfo> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_device {
        fn new_with_null_ptr() -> Self {
            Self {
                id: core::ptr::null_mut(),
                name: core::ptr::null_mut(),
                device_type: core::ptr::null_mut(),
                address: core::ptr::null_mut(),
                protocol: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_device {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_event {
        fn new_with_null_ptr() -> Self {
            Self {
                tag: -1,
                kind: FfiEventKind { nil__: () },
            }
        }
    }
    impl Default for wire_cst_ffi_event {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_file_info {
        fn new_with_null_ptr() -> Self {
            Self {
                id: core::ptr::null_mut(),
                name: core::ptr::null_mut(),
                size: Default::default(),
                mime_type: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_file_info {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_local_info {
        fn new_with_null_ptr() -> Self {
            Self {
                device_name: core::ptr::null_mut(),
                save_dir: core::ptr::null_mut(),
                protocols: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_local_info {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_transfer_progress {
        fn new_with_null_ptr() -> Self {
            Self {
                transfer_id: core::ptr::null_mut(),
                file_name: core::ptr::null_mut(),
                bytes_sent: Default::default(),
                total_bytes: Default::default(),
                progress: Default::default(),
            }
        }
    }
    impl Default for wire_cst_ffi_transfer_progress {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_transfer_request {
        fn new_with_null_ptr() -> Self {
            Self {
                request_id: core::ptr::null_mut(),
                from_device: Default::default(),
                files: core::ptr::null_mut(),
                total_size: Default::default(),
            }
        }
    }
    impl Default for wire_cst_ffi_transfer_request {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__accept_transfer(
        port_: i64,
        request_id: *mut wire_cst_list_prim_u_8_strict,
        protocol: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__accept_transfer_impl(port_, request_id, protocol)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__get_devices(port_: i64) {
        wire__crate__api__get_devices_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__get_protocols(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_protocols_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__init_engine(
        device_name: *mut wire_cst_list_prim_u_8_strict,
        save_dir: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__init_engine_impl(device_name, save_dir)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__is_engine_running(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__is_engine_running_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__reject_transfer(
        port_: i64,
        request_id: *mut wire_cst_list_prim_u_8_strict,
        protocol: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__reject_transfer_impl(port_, request_id, protocol)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__scan_devices(port_: i64) {
        wire__crate__api__scan_devices_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__send_files(
        port_: i64,
        device_id: *mut wire_cst_list_prim_u_8_strict,
        file_paths: *mut wire_cst_list_String,
    ) {
        wire__crate__api__send_files_impl(port_, device_id, file_paths)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__start_engine(port_: i64) {
        wire__crate__api__start_engine_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__stop_engine(port_: i64) {
        wire__crate__api__stop_engine_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_wire__crate__api__subscribe_events(
        port_: i64,
        callback: *const std::ffi::c_void,
    ) {
        wire__crate__api__subscribe_events_impl(port_, callback)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_box_autoadd_ffi_device() -> *mut wire_cst_ffi_device
    {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_ffi_device::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_box_autoadd_ffi_transfer_progress(
    ) -> *mut wire_cst_ffi_transfer_progress {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_ffi_transfer_progress::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_box_autoadd_ffi_transfer_request(
    ) -> *mut wire_cst_ffi_transfer_request {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_ffi_transfer_request::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_list_String(
        len: i32,
    ) -> *mut wire_cst_list_String {
        let wrap = wire_cst_list_String {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <*mut wire_cst_list_prim_u_8_strict>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_list_ffi_device(
        len: i32,
    ) -> *mut wire_cst_list_ffi_device {
        let wrap = wire_cst_list_ffi_device {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_ffi_device>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_list_ffi_file_info(
        len: i32,
    ) -> *mut wire_cst_list_ffi_file_info {
        let wrap = wire_cst_list_ffi_file_info {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_ffi_file_info>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_unidrop_app_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_device {
        id: *mut wire_cst_list_prim_u_8_strict,
        name: *mut wire_cst_list_prim_u_8_strict,
        device_type: *mut wire_cst_list_prim_u_8_strict,
        address: *mut wire_cst_list_prim_u_8_strict,
        protocol: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_event {
        tag: i32,
        kind: FfiEventKind,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub union FfiEventKind {
        DeviceDiscovered: wire_cst_FfiEvent_DeviceDiscovered,
        DeviceLost: wire_cst_FfiEvent_DeviceLost,
        TransferRequested: wire_cst_FfiEvent_TransferRequested,
        TransferProgress: wire_cst_FfiEvent_TransferProgress,
        TransferCompleted: wire_cst_FfiEvent_TransferCompleted,
        TransferFailed: wire_cst_FfiEvent_TransferFailed,
        Error: wire_cst_FfiEvent_Error,
        nil__: (),
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_DeviceDiscovered {
        device: *mut wire_cst_ffi_device,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_DeviceLost {
        device_id: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_TransferRequested {
        request: *mut wire_cst_ffi_transfer_request,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_TransferProgress {
        progress: *mut wire_cst_ffi_transfer_progress,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_TransferCompleted {
        transfer_id: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_TransferFailed {
        transfer_id: *mut wire_cst_list_prim_u_8_strict,
        error: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_FfiEvent_Error {
        message: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_file_info {
        id: *mut wire_cst_list_prim_u_8_strict,
        name: *mut wire_cst_list_prim_u_8_strict,
        size: u64,
        mime_type: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_local_info {
        device_name: *mut wire_cst_list_prim_u_8_strict,
        save_dir: *mut wire_cst_list_prim_u_8_strict,
        protocols: *mut wire_cst_list_String,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_transfer_progress {
        transfer_id: *mut wire_cst_list_prim_u_8_strict,
        file_name: *mut wire_cst_list_prim_u_8_strict,
        bytes_sent: u64,
        total_bytes: u64,
        progress: f64,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_transfer_request {
        request_id: *mut wire_cst_list_prim_u_8_strict,
        from_device: wire_cst_ffi_device,
        files: *mut wire_cst_list_ffi_file_info,
        total_size: u64,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_String {
        ptr: *mut *mut wire_cst_list_prim_u_8_strict,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_ffi_device {
        ptr: *mut wire_cst_ffi_device,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_ffi_file_info {
        ptr: *mut wire_cst_ffi_file_info,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<flutter_rust_bridge::DartOpaque>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::DartOpaque {
            unsafe { flutter_rust_bridge::for_generated::cst_decode_dart_opaque(self as _) }
        }
    }
    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<crate::api::FfiDevice>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiDevice {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                5,
                "Expected 5 elements, got {}",
                self_.length()
            );
            crate::api::FfiDevice {
                id: self_.get(0).cst_decode(),
                name: self_.get(1).cst_decode(),
                device_type: self_.get(2).cst_decode(),
                address: self_.get(3).cst_decode(),
                protocol: self_.get(4).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiEvent> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiEvent {
            let self_ = self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Array>();
            match self_.get(0).unchecked_into_f64() as _ {
                0 => crate::api::FfiEvent::DeviceDiscovered {
                    device: self_.get(1).cst_decode(),
                },
                1 => crate::api::FfiEvent::DeviceLost {
                    device_id: self_.get(1).cst_decode(),
                },
                2 => crate::api::FfiEvent::TransferRequested {
                    request: self_.get(1).cst_decode(),
                },
                3 => crate::api::FfiEvent::TransferProgress {
                    progress: self_.get(1).cst_decode(),
                },
                4 => crate::api::FfiEvent::TransferCompleted {
                    transfer_id: self_.get(1).cst_decode(),
                },
                5 => crate::api::FfiEvent::TransferFailed {
                    transfer_id: self_.get(1).cst_decode(),
                    error: self_.get(2).cst_decode(),
                },
                6 => crate::api::FfiEvent::Error {
                    message: self_.get(1).cst_decode(),
                },
                _ => unreachable!(),
            }
        }
    }
    impl CstDecode<crate::api::FfiFileInfo>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiFileInfo {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                4,
                "Expected 4 elements, got {}",
                self_.length()
            );
            crate::api::FfiFileInfo {
                id: self_.get(0).cst_decode(),
                name: self_.get(1).cst_decode(),
                size: self_.get(2).cst_decode(),
                mime_type: self_.get(3).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiLocalInfo>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiLocalInfo {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::FfiLocalInfo {
                device_name: self_.get(0).cst_decode(),
                save_dir: self_.get(1).cst_decode(),
                protocols: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiTransferProgress>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiTransferProgress {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                5,
                "Expected 5 elements, got {}",
                self_.length()
            );
            crate::api::FfiTransferProgress {
                transfer_id: self_.get(0).cst_decode(),
                file_name: self_.get(1).cst_decode(),
                bytes_sent: self_.get(2).cst_decode(),
                total_bytes: self_.get(3).cst_decode(),
                progress: self_.get(4).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::FfiTransferRequest>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::FfiTransferRequest {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                4,
                "Expected 4 elements, got {}",
                self_.length()
            );
            crate::api::FfiTransferRequest {
                request_id: self_.get(0).cst_decode(),
                from_device: self_.get(1).cst_decode(),
                files: self_.get(2).cst_decode(),
                total_size: self_.get(3).cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<String>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<crate::api::FfiDevice>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::FfiDevice> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<crate::api::FfiFileInfo>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::FfiFileInfo> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<Option<String>> for Option<String> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<String> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bool {
            self.is_truthy()
        }
    }
    impl CstDecode<f64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> f64 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<isize> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> isize {
            ::std::convert::TryInto::<i64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<u64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<usize> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> usize {
            ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__accept_transfer(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        request_id: String,
        protocol: String,
    ) {
        wire__crate__api__accept_transfer_impl(port_, request_id, protocol)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_devices(port_: flutter_rust_bridge::for_generated::MessagePort) {
        wire__crate__api__get_devices_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_protocols(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_protocols_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__init_engine(
        device_name: Option<String>,
        save_dir: Option<String>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__init_engine_impl(device_name, save_dir)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__is_engine_running(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__is_engine_running_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__reject_transfer(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        request_id: String,
        protocol: String,
    ) {
        wire__crate__api__reject_transfer_impl(port_, request_id, protocol)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__scan_devices(port_: flutter_rust_bridge::for_generated::MessagePort) {
        wire__crate__api__scan_devices_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__send_files(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        device_id: String,
        file_paths: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__send_files_impl(port_, device_id, file_paths)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__start_engine(port_: flutter_rust_bridge::for_generated::MessagePort) {
        wire__crate__api__start_engine_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__stop_engine(port_: flutter_rust_bridge::for_generated::MessagePort) {
        wire__crate__api__stop_engine_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__subscribe_events(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        callback: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__subscribe_events_impl(port_, callback)
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
