// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_event`, `get_engine`, `get_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ENGINE`, `RUNTIME`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

/// 初始化 UniDrop 引擎
FfiLocalInfo initEngine({String? deviceName, String? saveDir}) =>
    RustLib.instance.api
        .crateApiInitEngine(deviceName: deviceName, saveDir: saveDir);

/// 启动引擎
Future<void> startEngine() => RustLib.instance.api.crateApiStartEngine();

/// 停止引擎
Future<void> stopEngine() => RustLib.instance.api.crateApiStopEngine();

/// 获取在线设备列表
Future<List<FfiDevice>> getDevices() =>
    RustLib.instance.api.crateApiGetDevices();

/// 扫描设备
Future<void> scanDevices() => RustLib.instance.api.crateApiScanDevices();

/// 发送文件
Future<String> sendFiles(
        {required String deviceId, required List<String> filePaths}) =>
    RustLib.instance.api
        .crateApiSendFiles(deviceId: deviceId, filePaths: filePaths);

/// 接受传输请求
Future<void> acceptTransfer(
        {required String requestId, required String protocol}) =>
    RustLib.instance.api
        .crateApiAcceptTransfer(requestId: requestId, protocol: protocol);

/// 拒绝传输请求
Future<void> rejectTransfer(
        {required String requestId, required String protocol}) =>
    RustLib.instance.api
        .crateApiRejectTransfer(requestId: requestId, protocol: protocol);

/// 订阅事件流 - 通过回调函数接收事件
Future<void> subscribeEvents(
        {required FutureOr<void> Function(FfiEvent) callback}) =>
    RustLib.instance.api.crateApiSubscribeEvents(callback: callback);

/// 获取协议列表
List<String> getProtocols() => RustLib.instance.api.crateApiGetProtocols();

/// 检查引擎是否正在运行
bool isEngineRunning() => RustLib.instance.api.crateApiIsEngineRunning();

/// 设备信息
@freezed
sealed class FfiDevice with _$FfiDevice {
  const factory FfiDevice({
    required String id,
    required String name,
    required String deviceType,
    required String address,
    required String protocol,
  }) = _FfiDevice;
}

@freezed
sealed class FfiEvent with _$FfiEvent {
  const FfiEvent._();

  /// 发现设备
  const factory FfiEvent.deviceDiscovered({
    required FfiDevice device,
  }) = FfiEvent_DeviceDiscovered;

  /// 设备离线
  const factory FfiEvent.deviceLost({
    required String deviceId,
  }) = FfiEvent_DeviceLost;

  /// 收到传输请求
  const factory FfiEvent.transferRequested({
    required FfiTransferRequest request,
  }) = FfiEvent_TransferRequested;

  /// 传输进度
  const factory FfiEvent.transferProgress({
    required FfiTransferProgress progress,
  }) = FfiEvent_TransferProgress;

  /// 传输完成
  const factory FfiEvent.transferCompleted({
    required String transferId,
  }) = FfiEvent_TransferCompleted;

  /// 传输失败
  const factory FfiEvent.transferFailed({
    required String transferId,
    required String error,
  }) = FfiEvent_TransferFailed;

  /// 错误
  const factory FfiEvent.error({
    required String message,
  }) = FfiEvent_Error;
}

/// 文件信息
@freezed
sealed class FfiFileInfo with _$FfiFileInfo {
  const factory FfiFileInfo({
    required String id,
    required String name,
    required BigInt size,
    String? mimeType,
  }) = _FfiFileInfo;
}

/// 本机信息
@freezed
sealed class FfiLocalInfo with _$FfiLocalInfo {
  const factory FfiLocalInfo({
    required String deviceName,
    required String saveDir,
    required List<String> protocols,
  }) = _FfiLocalInfo;
}

/// 传输状态
@freezed
sealed class FfiTransferProgress with _$FfiTransferProgress {
  const factory FfiTransferProgress({
    required String transferId,
    required String fileName,
    required BigInt bytesSent,
    required BigInt totalBytes,
    required double progress,
  }) = _FfiTransferProgress;
}

/// 传输请求
@freezed
sealed class FfiTransferRequest with _$FfiTransferRequest {
  const factory FfiTransferRequest({
    required String requestId,
    required FfiDevice fromDevice,
    required List<FfiFileInfo> files,
    required BigInt totalSize,
  }) = _FfiTransferRequest;
}
