// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(FfiEvent)
      dco_decode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiDevice dco_decode_box_autoadd_ffi_device(dynamic raw);

  @protected
  FfiTransferProgress dco_decode_box_autoadd_ffi_transfer_progress(dynamic raw);

  @protected
  FfiTransferRequest dco_decode_box_autoadd_ffi_transfer_request(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiDevice dco_decode_ffi_device(dynamic raw);

  @protected
  FfiEvent dco_decode_ffi_event(dynamic raw);

  @protected
  FfiFileInfo dco_decode_ffi_file_info(dynamic raw);

  @protected
  FfiLocalInfo dco_decode_ffi_local_info(dynamic raw);

  @protected
  FfiTransferProgress dco_decode_ffi_transfer_progress(dynamic raw);

  @protected
  FfiTransferRequest dco_decode_ffi_transfer_request(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiDevice> dco_decode_list_ffi_device(dynamic raw);

  @protected
  List<FfiFileInfo> dco_decode_list_ffi_file_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiDevice sse_decode_box_autoadd_ffi_device(SseDeserializer deserializer);

  @protected
  FfiTransferProgress sse_decode_box_autoadd_ffi_transfer_progress(
      SseDeserializer deserializer);

  @protected
  FfiTransferRequest sse_decode_box_autoadd_ffi_transfer_request(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiDevice sse_decode_ffi_device(SseDeserializer deserializer);

  @protected
  FfiEvent sse_decode_ffi_event(SseDeserializer deserializer);

  @protected
  FfiFileInfo sse_decode_ffi_file_info(SseDeserializer deserializer);

  @protected
  FfiLocalInfo sse_decode_ffi_local_info(SseDeserializer deserializer);

  @protected
  FfiTransferProgress sse_decode_ffi_transfer_progress(
      SseDeserializer deserializer);

  @protected
  FfiTransferRequest sse_decode_ffi_transfer_request(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiDevice> sse_decode_list_ffi_device(SseDeserializer deserializer);

  @protected
  List<FfiFileInfo> sse_decode_list_ffi_file_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
      AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_ffi_device> cst_encode_box_autoadd_ffi_device(
      FfiDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_ffi_device();
    cst_api_fill_to_wire_ffi_device(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_ffi_transfer_progress>
      cst_encode_box_autoadd_ffi_transfer_progress(FfiTransferProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_ffi_transfer_progress();
    cst_api_fill_to_wire_ffi_transfer_progress(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_ffi_transfer_request>
      cst_encode_box_autoadd_ffi_transfer_request(FfiTransferRequest raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_ffi_transfer_request();
    cst_api_fill_to_wire_ffi_transfer_request(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_isize(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ffi_device> cst_encode_list_ffi_device(
      List<FfiDevice> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ffi_device(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ffi_device(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ffi_file_info> cst_encode_list_ffi_file_info(
      List<FfiFileInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ffi_file_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ffi_file_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_ffi_device(
      FfiDevice apiObj, ffi.Pointer<wire_cst_ffi_device> wireObj) {
    cst_api_fill_to_wire_ffi_device(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_ffi_transfer_progress(
      FfiTransferProgress apiObj,
      ffi.Pointer<wire_cst_ffi_transfer_progress> wireObj) {
    cst_api_fill_to_wire_ffi_transfer_progress(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_ffi_transfer_request(
      FfiTransferRequest apiObj,
      ffi.Pointer<wire_cst_ffi_transfer_request> wireObj) {
    cst_api_fill_to_wire_ffi_transfer_request(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_ffi_device(
      FfiDevice apiObj, wire_cst_ffi_device wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.device_type = cst_encode_String(apiObj.deviceType);
    wireObj.address = cst_encode_String(apiObj.address);
    wireObj.protocol = cst_encode_String(apiObj.protocol);
  }

  @protected
  void cst_api_fill_to_wire_ffi_event(
      FfiEvent apiObj, wire_cst_ffi_event wireObj) {
    if (apiObj is FfiEvent_DeviceDiscovered) {
      var pre_device = cst_encode_box_autoadd_ffi_device(apiObj.device);
      wireObj.tag = 0;
      wireObj.kind.DeviceDiscovered.device = pre_device;
      return;
    }
    if (apiObj is FfiEvent_DeviceLost) {
      var pre_device_id = cst_encode_String(apiObj.deviceId);
      wireObj.tag = 1;
      wireObj.kind.DeviceLost.device_id = pre_device_id;
      return;
    }
    if (apiObj is FfiEvent_TransferRequested) {
      var pre_request =
          cst_encode_box_autoadd_ffi_transfer_request(apiObj.request);
      wireObj.tag = 2;
      wireObj.kind.TransferRequested.request = pre_request;
      return;
    }
    if (apiObj is FfiEvent_TransferProgress) {
      var pre_progress =
          cst_encode_box_autoadd_ffi_transfer_progress(apiObj.progress);
      wireObj.tag = 3;
      wireObj.kind.TransferProgress.progress = pre_progress;
      return;
    }
    if (apiObj is FfiEvent_TransferCompleted) {
      var pre_transfer_id = cst_encode_String(apiObj.transferId);
      wireObj.tag = 4;
      wireObj.kind.TransferCompleted.transfer_id = pre_transfer_id;
      return;
    }
    if (apiObj is FfiEvent_TransferFailed) {
      var pre_transfer_id = cst_encode_String(apiObj.transferId);
      var pre_error = cst_encode_String(apiObj.error);
      wireObj.tag = 5;
      wireObj.kind.TransferFailed.transfer_id = pre_transfer_id;
      wireObj.kind.TransferFailed.error = pre_error;
      return;
    }
    if (apiObj is FfiEvent_Error) {
      var pre_message = cst_encode_String(apiObj.message);
      wireObj.tag = 6;
      wireObj.kind.Error.message = pre_message;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_ffi_file_info(
      FfiFileInfo apiObj, wire_cst_ffi_file_info wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.size = cst_encode_u_64(apiObj.size);
    wireObj.mime_type = cst_encode_opt_String(apiObj.mimeType);
  }

  @protected
  void cst_api_fill_to_wire_ffi_local_info(
      FfiLocalInfo apiObj, wire_cst_ffi_local_info wireObj) {
    wireObj.device_name = cst_encode_String(apiObj.deviceName);
    wireObj.save_dir = cst_encode_String(apiObj.saveDir);
    wireObj.protocols = cst_encode_list_String(apiObj.protocols);
  }

  @protected
  void cst_api_fill_to_wire_ffi_transfer_progress(
      FfiTransferProgress apiObj, wire_cst_ffi_transfer_progress wireObj) {
    wireObj.transfer_id = cst_encode_String(apiObj.transferId);
    wireObj.file_name = cst_encode_String(apiObj.fileName);
    wireObj.bytes_sent = cst_encode_u_64(apiObj.bytesSent);
    wireObj.total_bytes = cst_encode_u_64(apiObj.totalBytes);
    wireObj.progress = cst_encode_f_64(apiObj.progress);
  }

  @protected
  void cst_api_fill_to_wire_ffi_transfer_request(
      FfiTransferRequest apiObj, wire_cst_ffi_transfer_request wireObj) {
    wireObj.request_id = cst_encode_String(apiObj.requestId);
    cst_api_fill_to_wire_ffi_device(apiObj.fromDevice, wireObj.from_device);
    wireObj.files = cst_encode_list_ffi_file_info(apiObj.files);
    wireObj.total_size = cst_encode_u_64(apiObj.totalSize);
  }

  @protected
  PlatformPointer
      cst_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          FutureOr<void> Function(FfiEvent) raw);

  @protected
  PlatformPointer cst_encode_DartOpaque(Object raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
      FutureOr<void> Function(FfiEvent) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_device(
      FfiDevice self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_transfer_progress(
      FfiTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_transfer_request(
      FfiTransferRequest self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_device(FfiDevice self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_event(FfiEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_file_info(FfiFileInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_local_info(FfiLocalInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_transfer_progress(
      FfiTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_transfer_request(
      FfiTransferRequest self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_device(
      List<FfiDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_file_info(
      List<FfiFileInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__accept_transfer(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> request_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> protocol,
  ) {
    return _wire__crate__api__accept_transfer(port_, request_id, protocol);
  }

  late final _wire__crate__api__accept_transferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_unidrop_app_wire__crate__api__accept_transfer');
  late final _wire__crate__api__accept_transfer =
      _wire__crate__api__accept_transferPtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  void wire__crate__api__get_devices(int port_) {
    return _wire__crate__api__get_devices(port_);
  }

  late final _wire__crate__api__get_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_unidrop_app_wire__crate__api__get_devices',
  );
  late final _wire__crate__api__get_devices =
      _wire__crate__api__get_devicesPtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__get_protocols() {
    return _wire__crate__api__get_protocols();
  }

  late final _wire__crate__api__get_protocolsPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
    'frbgen_unidrop_app_wire__crate__api__get_protocols',
  );
  late final _wire__crate__api__get_protocols =
      _wire__crate__api__get_protocolsPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__init_engine(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> device_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> save_dir,
  ) {
    return _wire__crate__api__init_engine(device_name, save_dir);
  }

  late final _wire__crate__api__init_enginePtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_unidrop_app_wire__crate__api__init_engine');
  late final _wire__crate__api__init_engine =
      _wire__crate__api__init_enginePtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__is_engine_running() {
    return _wire__crate__api__is_engine_running();
  }

  late final _wire__crate__api__is_engine_runningPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
    'frbgen_unidrop_app_wire__crate__api__is_engine_running',
  );
  late final _wire__crate__api__is_engine_running =
      _wire__crate__api__is_engine_runningPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__reject_transfer(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> request_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> protocol,
  ) {
    return _wire__crate__api__reject_transfer(port_, request_id, protocol);
  }

  late final _wire__crate__api__reject_transferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_unidrop_app_wire__crate__api__reject_transfer');
  late final _wire__crate__api__reject_transfer =
      _wire__crate__api__reject_transferPtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  void wire__crate__api__scan_devices(int port_) {
    return _wire__crate__api__scan_devices(port_);
  }

  late final _wire__crate__api__scan_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_unidrop_app_wire__crate__api__scan_devices',
  );
  late final _wire__crate__api__scan_devices =
      _wire__crate__api__scan_devicesPtr.asFunction<void Function(int)>();

  void wire__crate__api__send_files(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> device_id,
    ffi.Pointer<wire_cst_list_String> file_paths,
  ) {
    return _wire__crate__api__send_files(port_, device_id, file_paths);
  }

  late final _wire__crate__api__send_filesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
          )>>('frbgen_unidrop_app_wire__crate__api__send_files');
  late final _wire__crate__api__send_files =
      _wire__crate__api__send_filesPtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
          )>();

  void wire__crate__api__start_engine(int port_) {
    return _wire__crate__api__start_engine(port_);
  }

  late final _wire__crate__api__start_enginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_unidrop_app_wire__crate__api__start_engine',
  );
  late final _wire__crate__api__start_engine =
      _wire__crate__api__start_enginePtr.asFunction<void Function(int)>();

  void wire__crate__api__stop_engine(int port_) {
    return _wire__crate__api__stop_engine(port_);
  }

  late final _wire__crate__api__stop_enginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_unidrop_app_wire__crate__api__stop_engine',
  );
  late final _wire__crate__api__stop_engine =
      _wire__crate__api__stop_enginePtr.asFunction<void Function(int)>();

  void wire__crate__api__subscribe_events(
    int port_,
    ffi.Pointer<ffi.Void> callback,
  ) {
    return _wire__crate__api__subscribe_events(port_, callback);
  }

  late final _wire__crate__api__subscribe_eventsPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Void>)>>(
      'frbgen_unidrop_app_wire__crate__api__subscribe_events');
  late final _wire__crate__api__subscribe_events =
      _wire__crate__api__subscribe_eventsPtr
          .asFunction<void Function(int, ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_ffi_device> cst_new_box_autoadd_ffi_device() {
    return _cst_new_box_autoadd_ffi_device();
  }

  late final _cst_new_box_autoadd_ffi_devicePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_ffi_device> Function()>>(
    'frbgen_unidrop_app_cst_new_box_autoadd_ffi_device',
  );
  late final _cst_new_box_autoadd_ffi_device =
      _cst_new_box_autoadd_ffi_devicePtr
          .asFunction<ffi.Pointer<wire_cst_ffi_device> Function()>();

  ffi.Pointer<wire_cst_ffi_transfer_progress>
      cst_new_box_autoadd_ffi_transfer_progress() {
    return _cst_new_box_autoadd_ffi_transfer_progress();
  }

  late final _cst_new_box_autoadd_ffi_transfer_progressPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_ffi_transfer_progress> Function()>>(
      'frbgen_unidrop_app_cst_new_box_autoadd_ffi_transfer_progress');
  late final _cst_new_box_autoadd_ffi_transfer_progress =
      _cst_new_box_autoadd_ffi_transfer_progressPtr
          .asFunction<ffi.Pointer<wire_cst_ffi_transfer_progress> Function()>();

  ffi.Pointer<wire_cst_ffi_transfer_request>
      cst_new_box_autoadd_ffi_transfer_request() {
    return _cst_new_box_autoadd_ffi_transfer_request();
  }

  late final _cst_new_box_autoadd_ffi_transfer_requestPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_ffi_transfer_request> Function()>>(
      'frbgen_unidrop_app_cst_new_box_autoadd_ffi_transfer_request');
  late final _cst_new_box_autoadd_ffi_transfer_request =
      _cst_new_box_autoadd_ffi_transfer_requestPtr
          .asFunction<ffi.Pointer<wire_cst_ffi_transfer_request> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_unidrop_app_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_ffi_device> cst_new_list_ffi_device(int len) {
    return _cst_new_list_ffi_device(len);
  }

  late final _cst_new_list_ffi_devicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ffi_device> Function(
              ffi.Int32)>>('frbgen_unidrop_app_cst_new_list_ffi_device');
  late final _cst_new_list_ffi_device = _cst_new_list_ffi_devicePtr
      .asFunction<ffi.Pointer<wire_cst_list_ffi_device> Function(int)>();

  ffi.Pointer<wire_cst_list_ffi_file_info> cst_new_list_ffi_file_info(int len) {
    return _cst_new_list_ffi_file_info(len);
  }

  late final _cst_new_list_ffi_file_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ffi_file_info> Function(
              ffi.Int32)>>('frbgen_unidrop_app_cst_new_list_ffi_file_info');
  late final _cst_new_list_ffi_file_info = _cst_new_list_ffi_file_infoPtr
      .asFunction<ffi.Pointer<wire_cst_list_ffi_file_info> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_unidrop_app_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_ffi_device extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> device_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> address;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> protocol;
}

final class wire_cst_ffi_transfer_progress extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> transfer_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> file_name;

  @ffi.Uint64()
  external int bytes_sent;

  @ffi.Uint64()
  external int total_bytes;

  @ffi.Double()
  external double progress;
}

final class wire_cst_ffi_file_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  @ffi.Uint64()
  external int size;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> mime_type;
}

final class wire_cst_list_ffi_file_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_ffi_file_info> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_ffi_transfer_request extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> request_id;

  external wire_cst_ffi_device from_device;

  external ffi.Pointer<wire_cst_list_ffi_file_info> files;

  @ffi.Uint64()
  external int total_size;
}

final class wire_cst_list_ffi_device extends ffi.Struct {
  external ffi.Pointer<wire_cst_ffi_device> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_FfiEvent_DeviceDiscovered extends ffi.Struct {
  external ffi.Pointer<wire_cst_ffi_device> device;
}

final class wire_cst_FfiEvent_DeviceLost extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> device_id;
}

final class wire_cst_FfiEvent_TransferRequested extends ffi.Struct {
  external ffi.Pointer<wire_cst_ffi_transfer_request> request;
}

final class wire_cst_FfiEvent_TransferProgress extends ffi.Struct {
  external ffi.Pointer<wire_cst_ffi_transfer_progress> progress;
}

final class wire_cst_FfiEvent_TransferCompleted extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> transfer_id;
}

final class wire_cst_FfiEvent_TransferFailed extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> transfer_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> error;
}

final class wire_cst_FfiEvent_Error extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;
}

final class FfiEventKind extends ffi.Union {
  external wire_cst_FfiEvent_DeviceDiscovered DeviceDiscovered;

  external wire_cst_FfiEvent_DeviceLost DeviceLost;

  external wire_cst_FfiEvent_TransferRequested TransferRequested;

  external wire_cst_FfiEvent_TransferProgress TransferProgress;

  external wire_cst_FfiEvent_TransferCompleted TransferCompleted;

  external wire_cst_FfiEvent_TransferFailed TransferFailed;

  external wire_cst_FfiEvent_Error Error;
}

final class wire_cst_ffi_event extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external FfiEventKind kind;
}

final class wire_cst_ffi_local_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> device_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> save_dir;

  external ffi.Pointer<wire_cst_list_String> protocols;
}
