// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -305547460;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'unidrop_ffi',
    ioDirectory: '../crates/unidrop-ffi/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAcceptTransfer(
      {required String requestId, required String protocol});

  Future<List<FfiDevice>> crateApiGetDevices();

  List<String> crateApiGetProtocols();

  FfiLocalInfo crateApiInitEngine({String? deviceName, String? saveDir});

  bool crateApiIsEngineRunning();

  Future<void> crateApiRejectTransfer(
      {required String requestId, required String protocol});

  Future<void> crateApiScanDevices();

  Future<String> crateApiSendFiles(
      {required String deviceId, required List<String> filePaths});

  Future<void> crateApiStartEngine();

  Future<void> crateApiStopEngine();

  Future<void> crateApiSubscribeEvents(
      {required FutureOr<void> Function(FfiEvent) callback});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAcceptTransfer(
      {required String requestId, required String protocol}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(requestId);
        var arg1 = cst_encode_String(protocol);
        return wire.wire__crate__api__accept_transfer(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiAcceptTransferConstMeta,
      argValues: [requestId, protocol],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAcceptTransferConstMeta => const TaskConstMeta(
        debugName: "accept_transfer",
        argNames: ["requestId", "protocol"],
      );

  @override
  Future<List<FfiDevice>> crateApiGetDevices() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__get_devices(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_ffi_device,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiGetDevicesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDevicesConstMeta => const TaskConstMeta(
        debugName: "get_devices",
        argNames: [],
      );

  @override
  List<String> crateApiGetProtocols() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__get_protocols();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiGetProtocolsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetProtocolsConstMeta => const TaskConstMeta(
        debugName: "get_protocols",
        argNames: [],
      );

  @override
  FfiLocalInfo crateApiInitEngine({String? deviceName, String? saveDir}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_opt_String(deviceName);
        var arg1 = cst_encode_opt_String(saveDir);
        return wire.wire__crate__api__init_engine(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_ffi_local_info,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiInitEngineConstMeta,
      argValues: [deviceName, saveDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitEngineConstMeta => const TaskConstMeta(
        debugName: "init_engine",
        argNames: ["deviceName", "saveDir"],
      );

  @override
  bool crateApiIsEngineRunning() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__is_engine_running();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsEngineRunningConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsEngineRunningConstMeta => const TaskConstMeta(
        debugName: "is_engine_running",
        argNames: [],
      );

  @override
  Future<void> crateApiRejectTransfer(
      {required String requestId, required String protocol}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(requestId);
        var arg1 = cst_encode_String(protocol);
        return wire.wire__crate__api__reject_transfer(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiRejectTransferConstMeta,
      argValues: [requestId, protocol],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRejectTransferConstMeta => const TaskConstMeta(
        debugName: "reject_transfer",
        argNames: ["requestId", "protocol"],
      );

  @override
  Future<void> crateApiScanDevices() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__scan_devices(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiScanDevicesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiScanDevicesConstMeta => const TaskConstMeta(
        debugName: "scan_devices",
        argNames: [],
      );

  @override
  Future<String> crateApiSendFiles(
      {required String deviceId, required List<String> filePaths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(deviceId);
        var arg1 = cst_encode_list_String(filePaths);
        return wire.wire__crate__api__send_files(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiSendFilesConstMeta,
      argValues: [deviceId, filePaths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendFilesConstMeta => const TaskConstMeta(
        debugName: "send_files",
        argNames: ["deviceId", "filePaths"],
      );

  @override
  Future<void> crateApiStartEngine() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__start_engine(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiStartEngineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStartEngineConstMeta => const TaskConstMeta(
        debugName: "start_engine",
        argNames: [],
      );

  @override
  Future<void> crateApiStopEngine() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__stop_engine(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiStopEngineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStopEngineConstMeta => const TaskConstMeta(
        debugName: "stop_engine",
        argNames: [],
      );

  @override
  Future<void> crateApiSubscribeEvents(
      {required FutureOr<void> Function(FfiEvent) callback}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 =
            cst_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
                callback);
        return wire.wire__crate__api__subscribe_events(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiSubscribeEventsConstMeta,
      argValues: [callback],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSubscribeEventsConstMeta => const TaskConstMeta(
        debugName: "subscribe_events",
        argNames: ["callback"],
      );

  Future<void> Function(int, dynamic)
      encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          FutureOr<void> Function(FfiEvent) raw) {
    return (callId, rawArg0) async {
      final arg0 = dco_decode_ffi_event(rawArg0);

      Box<void>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_unit(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
          callId: callId,
          ptr: output.ptr,
          rustVecLen: output.rustVecLen,
          dataLen: output.dataLen);
    };
  }

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FutureOr<void> Function(FfiEvent)
      dco_decode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  Object dco_decode_DartOpaque(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return decodeDartOpaque(raw, generalizedFrbRustBinding);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiDevice dco_decode_box_autoadd_ffi_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_device(raw);
  }

  @protected
  FfiTransferProgress dco_decode_box_autoadd_ffi_transfer_progress(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_transfer_progress(raw);
  }

  @protected
  FfiTransferRequest dco_decode_box_autoadd_ffi_transfer_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_transfer_request(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfiDevice dco_decode_ffi_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FfiDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      deviceType: dco_decode_String(arr[2]),
      address: dco_decode_String(arr[3]),
      protocol: dco_decode_String(arr[4]),
    );
  }

  @protected
  FfiEvent dco_decode_ffi_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FfiEvent_DeviceDiscovered(
          device: dco_decode_box_autoadd_ffi_device(raw[1]),
        );
      case 1:
        return FfiEvent_DeviceLost(
          deviceId: dco_decode_String(raw[1]),
        );
      case 2:
        return FfiEvent_TransferRequested(
          request: dco_decode_box_autoadd_ffi_transfer_request(raw[1]),
        );
      case 3:
        return FfiEvent_TransferProgress(
          progress: dco_decode_box_autoadd_ffi_transfer_progress(raw[1]),
        );
      case 4:
        return FfiEvent_TransferCompleted(
          transferId: dco_decode_String(raw[1]),
        );
      case 5:
        return FfiEvent_TransferFailed(
          transferId: dco_decode_String(raw[1]),
          error: dco_decode_String(raw[2]),
        );
      case 6:
        return FfiEvent_Error(
          message: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  FfiFileInfo dco_decode_ffi_file_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiFileInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      mimeType: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FfiLocalInfo dco_decode_ffi_local_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiLocalInfo(
      deviceName: dco_decode_String(arr[0]),
      saveDir: dco_decode_String(arr[1]),
      protocols: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  FfiTransferProgress dco_decode_ffi_transfer_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FfiTransferProgress(
      transferId: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      bytesSent: dco_decode_u_64(arr[2]),
      totalBytes: dco_decode_u_64(arr[3]),
      progress: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  FfiTransferRequest dco_decode_ffi_transfer_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiTransferRequest(
      requestId: dco_decode_String(arr[0]),
      fromDevice: dco_decode_ffi_device(arr[1]),
      files: dco_decode_list_ffi_file_info(arr[2]),
      totalSize: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FfiDevice> dco_decode_list_ffi_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_device).toList();
  }

  @protected
  List<FfiFileInfo> dco_decode_list_ffi_file_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_file_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_isize(deserializer);
    return decodeDartOpaque(inner, generalizedFrbRustBinding);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiDevice sse_decode_box_autoadd_ffi_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_device(deserializer));
  }

  @protected
  FfiTransferProgress sse_decode_box_autoadd_ffi_transfer_progress(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_transfer_progress(deserializer));
  }

  @protected
  FfiTransferRequest sse_decode_box_autoadd_ffi_transfer_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_transfer_request(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FfiDevice sse_decode_ffi_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    return FfiDevice(
        id: var_id,
        name: var_name,
        deviceType: var_deviceType,
        address: var_address,
        protocol: var_protocol);
  }

  @protected
  FfiEvent sse_decode_ffi_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_device = sse_decode_box_autoadd_ffi_device(deserializer);
        return FfiEvent_DeviceDiscovered(device: var_device);
      case 1:
        var var_deviceId = sse_decode_String(deserializer);
        return FfiEvent_DeviceLost(deviceId: var_deviceId);
      case 2:
        var var_request =
            sse_decode_box_autoadd_ffi_transfer_request(deserializer);
        return FfiEvent_TransferRequested(request: var_request);
      case 3:
        var var_progress =
            sse_decode_box_autoadd_ffi_transfer_progress(deserializer);
        return FfiEvent_TransferProgress(progress: var_progress);
      case 4:
        var var_transferId = sse_decode_String(deserializer);
        return FfiEvent_TransferCompleted(transferId: var_transferId);
      case 5:
        var var_transferId = sse_decode_String(deserializer);
        var var_error = sse_decode_String(deserializer);
        return FfiEvent_TransferFailed(
            transferId: var_transferId, error: var_error);
      case 6:
        var var_message = sse_decode_String(deserializer);
        return FfiEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  FfiFileInfo sse_decode_ffi_file_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    return FfiFileInfo(
        id: var_id, name: var_name, size: var_size, mimeType: var_mimeType);
  }

  @protected
  FfiLocalInfo sse_decode_ffi_local_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceName = sse_decode_String(deserializer);
    var var_saveDir = sse_decode_String(deserializer);
    var var_protocols = sse_decode_list_String(deserializer);
    return FfiLocalInfo(
        deviceName: var_deviceName,
        saveDir: var_saveDir,
        protocols: var_protocols);
  }

  @protected
  FfiTransferProgress sse_decode_ffi_transfer_progress(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transferId = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_bytesSent = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    return FfiTransferProgress(
        transferId: var_transferId,
        fileName: var_fileName,
        bytesSent: var_bytesSent,
        totalBytes: var_totalBytes,
        progress: var_progress);
  }

  @protected
  FfiTransferRequest sse_decode_ffi_transfer_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_requestId = sse_decode_String(deserializer);
    var var_fromDevice = sse_decode_ffi_device(deserializer);
    var var_files = sse_decode_list_ffi_file_info(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return FfiTransferRequest(
        requestId: var_requestId,
        fromDevice: var_fromDevice,
        files: var_files,
        totalSize: var_totalSize);
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiDevice> sse_decode_list_ffi_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiFileInfo> sse_decode_list_ffi_file_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiFileInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_file_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformPointer
      cst_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          FutureOr<void> Function(FfiEvent) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_DartOpaque(
        encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(raw));
  }

  @protected
  PlatformPointer cst_encode_DartOpaque(Object raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return encodeDartOpaque(
        raw, portManager.dartHandlerPort, generalizedFrbRustBinding);
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
      FutureOr<void> Function(FfiEvent) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
        encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(self),
        serializer);
  }

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(
        PlatformPointerUtil.ptrToPlatformInt64(encodeDartOpaque(
            self, portManager.dartHandlerPort, generalizedFrbRustBinding)),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ffi_device(
      FfiDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_device(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_transfer_progress(
      FfiTransferProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_transfer_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_transfer_request(
      FfiTransferRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_transfer_request(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_ffi_device(FfiDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_String(self.protocol, serializer);
  }

  @protected
  void sse_encode_ffi_event(FfiEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FfiEvent_DeviceDiscovered(device: final device):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_ffi_device(device, serializer);
      case FfiEvent_DeviceLost(deviceId: final deviceId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(deviceId, serializer);
      case FfiEvent_TransferRequested(request: final request):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_ffi_transfer_request(request, serializer);
      case FfiEvent_TransferProgress(progress: final progress):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_ffi_transfer_progress(progress, serializer);
      case FfiEvent_TransferCompleted(transferId: final transferId):
        sse_encode_i_32(4, serializer);
        sse_encode_String(transferId, serializer);
      case FfiEvent_TransferFailed(
          transferId: final transferId,
          error: final error
        ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(transferId, serializer);
        sse_encode_String(error, serializer);
      case FfiEvent_Error(message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_ffi_file_info(FfiFileInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
  }

  @protected
  void sse_encode_ffi_local_info(FfiLocalInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.saveDir, serializer);
    sse_encode_list_String(self.protocols, serializer);
  }

  @protected
  void sse_encode_ffi_transfer_progress(
      FfiTransferProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transferId, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_64(self.bytesSent, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_f_64(self.progress, serializer);
  }

  @protected
  void sse_encode_ffi_transfer_request(
      FfiTransferRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.requestId, serializer);
    sse_encode_ffi_device(self.fromDevice, serializer);
    sse_encode_list_ffi_file_info(self.files, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_device(
      List<FfiDevice> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_file_info(
      List<FfiFileInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_file_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
