// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(FfiEvent)
      dco_decode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiDevice dco_decode_box_autoadd_ffi_device(dynamic raw);

  @protected
  FfiTransferProgress dco_decode_box_autoadd_ffi_transfer_progress(dynamic raw);

  @protected
  FfiTransferRequest dco_decode_box_autoadd_ffi_transfer_request(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiDevice dco_decode_ffi_device(dynamic raw);

  @protected
  FfiEvent dco_decode_ffi_event(dynamic raw);

  @protected
  FfiFileInfo dco_decode_ffi_file_info(dynamic raw);

  @protected
  FfiLocalInfo dco_decode_ffi_local_info(dynamic raw);

  @protected
  FfiTransferProgress dco_decode_ffi_transfer_progress(dynamic raw);

  @protected
  FfiTransferRequest dco_decode_ffi_transfer_request(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiDevice> dco_decode_list_ffi_device(dynamic raw);

  @protected
  List<FfiFileInfo> dco_decode_list_ffi_file_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiDevice sse_decode_box_autoadd_ffi_device(SseDeserializer deserializer);

  @protected
  FfiTransferProgress sse_decode_box_autoadd_ffi_transfer_progress(
      SseDeserializer deserializer);

  @protected
  FfiTransferRequest sse_decode_box_autoadd_ffi_transfer_request(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiDevice sse_decode_ffi_device(SseDeserializer deserializer);

  @protected
  FfiEvent sse_decode_ffi_event(SseDeserializer deserializer);

  @protected
  FfiFileInfo sse_decode_ffi_file_info(SseDeserializer deserializer);

  @protected
  FfiLocalInfo sse_decode_ffi_local_info(SseDeserializer deserializer);

  @protected
  FfiTransferProgress sse_decode_ffi_transfer_progress(
      SseDeserializer deserializer);

  @protected
  FfiTransferRequest sse_decode_ffi_transfer_request(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiDevice> sse_decode_list_ffi_device(SseDeserializer deserializer);

  @protected
  List<FfiFileInfo> sse_decode_list_ffi_file_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_ffi_device(FfiDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_ffi_device(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_ffi_transfer_progress(FfiTransferProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_ffi_transfer_progress(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_ffi_transfer_request(FfiTransferRequest raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_ffi_transfer_request(raw);
  }

  @protected
  JSAny cst_encode_ffi_device(FfiDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_String(raw.deviceType),
      cst_encode_String(raw.address),
      cst_encode_String(raw.protocol)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_ffi_event(FfiEvent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is FfiEvent_DeviceDiscovered) {
      return [0, cst_encode_box_autoadd_ffi_device(raw.device)].jsify()!;
    }
    if (raw is FfiEvent_DeviceLost) {
      return [1, cst_encode_String(raw.deviceId)].jsify()!;
    }
    if (raw is FfiEvent_TransferRequested) {
      return [2, cst_encode_box_autoadd_ffi_transfer_request(raw.request)]
          .jsify()!;
    }
    if (raw is FfiEvent_TransferProgress) {
      return [3, cst_encode_box_autoadd_ffi_transfer_progress(raw.progress)]
          .jsify()!;
    }
    if (raw is FfiEvent_TransferCompleted) {
      return [4, cst_encode_String(raw.transferId)].jsify()!;
    }
    if (raw is FfiEvent_TransferFailed) {
      return [
        5,
        cst_encode_String(raw.transferId),
        cst_encode_String(raw.error)
      ].jsify()!;
    }
    if (raw is FfiEvent_Error) {
      return [6, cst_encode_String(raw.message)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_ffi_file_info(FfiFileInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_u_64(raw.size),
      cst_encode_opt_String(raw.mimeType)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_ffi_local_info(FfiLocalInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.deviceName),
      cst_encode_String(raw.saveDir),
      cst_encode_list_String(raw.protocols)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_ffi_transfer_progress(FfiTransferProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.transferId),
      cst_encode_String(raw.fileName),
      cst_encode_u_64(raw.bytesSent),
      cst_encode_u_64(raw.totalBytes),
      cst_encode_f_64(raw.progress)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_ffi_transfer_request(FfiTransferRequest raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.requestId),
      cst_encode_ffi_device(raw.fromDevice),
      cst_encode_list_ffi_file_info(raw.files),
      cst_encode_u_64(raw.totalSize)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_isize(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_ffi_device(List<FfiDevice> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_ffi_device).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_ffi_file_info(List<FfiFileInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_ffi_file_info).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  PlatformPointer
      cst_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
          FutureOr<void> Function(FfiEvent) raw);

  @protected
  PlatformPointer cst_encode_DartOpaque(Object raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_ffi_event_Output_unit_AnyhowException(
      FutureOr<void> Function(FfiEvent) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_device(
      FfiDevice self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_transfer_progress(
      FfiTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_transfer_request(
      FfiTransferRequest self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_device(FfiDevice self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_event(FfiEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_file_info(FfiFileInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_local_info(FfiLocalInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_transfer_progress(
      FfiTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_transfer_request(
      FfiTransferRequest self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_device(
      List<FfiDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_file_info(
      List<FfiFileInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__accept_transfer(
          NativePortType port_, String request_id, String protocol) =>
      wasmModule.wire__crate__api__accept_transfer(port_, request_id, protocol);

  void wire__crate__api__get_devices(NativePortType port_) =>
      wasmModule.wire__crate__api__get_devices(port_);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_protocols() =>
          wasmModule.wire__crate__api__get_protocols();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__init_engine(String? device_name, String? save_dir) =>
          wasmModule.wire__crate__api__init_engine(device_name, save_dir);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__is_engine_running() =>
          wasmModule.wire__crate__api__is_engine_running();

  void wire__crate__api__reject_transfer(
          NativePortType port_, String request_id, String protocol) =>
      wasmModule.wire__crate__api__reject_transfer(port_, request_id, protocol);

  void wire__crate__api__scan_devices(NativePortType port_) =>
      wasmModule.wire__crate__api__scan_devices(port_);

  void wire__crate__api__send_files(
          NativePortType port_, String device_id, JSAny file_paths) =>
      wasmModule.wire__crate__api__send_files(port_, device_id, file_paths);

  void wire__crate__api__start_engine(NativePortType port_) =>
      wasmModule.wire__crate__api__start_engine(port_);

  void wire__crate__api__stop_engine(NativePortType port_) =>
      wasmModule.wire__crate__api__stop_engine(port_);

  void wire__crate__api__subscribe_events(
          NativePortType port_, PlatformPointer callback) =>
      wasmModule.wire__crate__api__subscribe_events(port_, callback);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__accept_transfer(
      NativePortType port_, String request_id, String protocol);

  external void wire__crate__api__get_devices(NativePortType port_);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_protocols();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__init_engine(String? device_name, String? save_dir);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__is_engine_running();

  external void wire__crate__api__reject_transfer(
      NativePortType port_, String request_id, String protocol);

  external void wire__crate__api__scan_devices(NativePortType port_);

  external void wire__crate__api__send_files(
      NativePortType port_, String device_id, JSAny file_paths);

  external void wire__crate__api__start_engine(NativePortType port_);

  external void wire__crate__api__stop_engine(NativePortType port_);

  external void wire__crate__api__subscribe_events(
      NativePortType port_, PlatformPointer callback);
}
